### PR TITLE
fix README.md gentoo instalation

### PR DESCRIPTION
**Pull request by mercuriete**
* Gentoo now provides a ebuild for 1.2 release

### CODE REVIEW

**Comment by mercuriete** [comment]
for more information go to this page:
https://packages.gentoo.org/packages/games-util/gamemode

**Comment by mercuriete** [comment]
another way to do it without the version is simply using the package name.
```bash
emerge --ask gamemode
```
or 
```
emerge --ask games-util/gamemode
```

**Comment by aejsmith** [comment]
Thanks for pointing this out, I've updated the instructions to include both the stable release and latest sources (6896861acae64498e3deba28c5145ba24e23e5b5).

**Comment by mercuriete** [comment]
Thanks @aejsmith 
You and feral keep linux great
:smile: :+1:

**Pull request closed without merging**
