### PR TITLE
Move to GitHub Actions

### PR DESCRIPTION
**Pull request by stephanlachnit**
Closes https://github.com/FeralInteractive/gamemode/issues/325.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Run: https://github.com/stephanlachnit/gamemode/actions/runs/872646846

**Comment by stephanlachnit** [comment]
@afayaz-feral This should be good to merge now. Here is the output of the run: https://github.com/stephanlachnit/gamemode/runs/2660255091

I tested the format check with a negative example, and it fails as expected. But I had to adjust the script, using `git-clang-format` would somehow fail. Game simulation also works, and so does the static analyser.

As you can see, the script currently fails. Since it runs at the end, I would still merge this and fix the issues found later (better a CI that fails at the end than one that doesn't even start properly).

**Comment by stephanlachnit** [comment]
Maybe relevant for the static analyser: https://clang-analyzer.llvm.org/faq.html#null_pointer

**Comment by afayaz-feral** [comment]
> better a CI that fails at the end than one that doesn't even start properly

Agreed. I'll merge this now - apologies for the delay.

**Pull request merged**
