### PR TITLE
Change copyright year to 2020

### PR DESCRIPTION
**Pull request by psypherium**
Change copyright year to 2020

### CODE REVIEW

**Comment by ZachBacon** [comment]
do you need two pull requests that modifies the same file?

**Comment by psypherium** [comment]
They aren't the same file. I'm not good at github, sorry.

**Comment by ZachBacon** [comment]
My bad, you're right. Could of been done in one pr, but in due time you'll get the hang of it

**Comment by stephanlachnit** [comment]
> They aren't the same file.

Should still be in the same commit.

> One is the license file, one is the readme file. I'm not good at github, sorry.

You probably edited the files directly at github. However, you should do stuff like stiff with the `git` command. You maybe need to install git. Clone a clean fork (delete your repository and clone it again to get a clean fork), edit all the copyright years and run `git add <file>` for all changed files, and finally commit it with `git commit`, and push it with `git push`. Then you open a new PR.

**Comment by afayaz-feral** [comment]
Thanks for the PR, but I've opted to make the equivalent change myself. This is too trivial a change to be split across multiple commits let alone multiple PRs. Also I worry whether there are legal implications of a non-Feral employee updating the copyright year, best not to risk it.

**Pull request closed without merging**
